coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "foxhole_stockpiles/gui/**"
  - "foxhole_stockpiles/commands/gui/**"
